name = "wajibati"
compatibility_date = "2026-05-31"
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "wajibati-db"
database_id = "713bdfe5-e4a5-4be7-bad3-9e316e936d4f"
